### ISSUE TITLE
Failed to load the tree-view-menu package

### ISSUE THREAD

**Issue by Nickopanther** [yubaoquan/tree-view-menu#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tree-view-menu](https://github.com/yubaoquan/tree-view-menu) package 1.2.1

### Stack Trace

Failed to load the tree-view-menu package

```
At Cannot find module 'is-git-repository'

Error: Cannot find module 'is-git-repository'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.24.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.24.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/tree-view-menu/lib/util/util.js:5:30)
    at /packages/tree-view-menu/lib/util/util.js:150:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.24.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/tree-view-menu/lib/constant.js:7:17)
    at /packages/tree-view-menu/lib/constant.js:162:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.24.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/tree-view-menu/lib/config.js:9:17)
    at /packages/tree-view-menu/lib/config.js:99:22)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.24.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
```

### Non-Core Packages

```
beautify 0.31.0 
es6-javascript 1.0.0 
tree-view-sort 0.8.2 
linter-spell-javascript 0.9.0 
platformio-ide-terminal 2.8.0 
run-command 0.5.0 
teletype 0.8.0 
tree-view-menu 1.2.1 
```

**Comment by yubaoquan** [comment]
It seems this bug is related to some inner dependencies. I'm not going to find out what is wrong with this package. In fact, I have already switched to vscode. Because atom team is too lazy on developing some important features and fix some frequent bugs.

**Comment by jerome-diver** [comment]
i have thge same problem. I really would like to fix this, maybe someone here can feel himself concerned by this module dependency problem ? please...
I'm on archlinux

**Comment by yubaoquan** [comment]
I reviewed dependencies tree of this package, and I didn't find any dependency importing the 'is-git-repository'. This is the dependency tree
```
tree-view-menu@1.2.1 c:\Users\ywx653832\Downloads\tree-view-menu-master
+-- clipboardy@1.2.3
| +-- arch@2.1.1
| `-- execa@0.8.0
|   +-- cross-spawn@5.1.0
|   | +-- lru-cache@4.1.5
|   | | +-- pseudomap@1.0.2
|   | | `-- yallist@2.1.2
|   | +-- shebang-command@1.2.0
|   | | `-- shebang-regex@1.0.0
|   | `-- which@1.3.1
|   |   `-- isexe@2.0.0
|   +-- get-stream@3.0.0
|   +-- is-stream@1.1.0
|   +-- npm-run-path@2.0.2
|   | `-- path-key@2.0.1
|   +-- p-finally@1.0.0
|   +-- signal-exit@3.0.2
|   `-- strip-eof@1.0.0
+-- copy-dir@0.3.0
| `-- mkdir-p@0.0.7
+-- cpy@5.1.0
| +-- arrify@1.0.1
| +-- cp-file@4.2.0
| | +-- graceful-fs@4.1.15
| | +-- make-dir@1.3.0
| | | `-- pify@3.0.0
| | +-- nested-error-stacks@2.1.0 deduped
| | +-- pify@2.3.0
| | `-- safe-buffer@5.1.2
| +-- globby@6.1.0
| | +-- array-union@1.0.2
| | | `-- array-uniq@1.0.3
| | +-- glob@7.1.3
| | | +-- fs.realpath@1.0.0
| | | +-- inflight@1.0.6
| | | | +-- once@1.4.0 deduped
| | | | `-- wrappy@1.0.2
| | | +-- inherits@2.0.3
| | | +-- minimatch@3.0.4 deduped
| | | +-- once@1.4.0
| | | | `-- wrappy@1.0.2 deduped
| | | `-- path-is-absolute@1.0.1 deduped
| | +-- object-assign@4.1.1
| | +-- pify@2.3.0 deduped
| | `-- pinkie-promise@2.0.1
| |   `-- pinkie@2.0.4
| `-- nested-error-stacks@2.1.0
+-- mv@2.1.1
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- ncp@2.0.0
| `-- rimraf@2.4.5
|   `-- glob@6.0.4
|     +-- inflight@1.0.6 deduped
|     +-- inherits@2.0.3 deduped
|     +-- minimatch@3.0.4 deduped
|     +-- once@1.4.0 deduped
|     `-- path-is-absolute@1.0.1 deduped
+-- recursive-readdir@2.2.2
| `-- minimatch@3.0.4
|   `-- brace-expansion@1.1.11
|     +-- balanced-match@1.0.0
|     `-- concat-map@0.0.1
`-- trash@4.3.0
  +-- escape-string-applescript@2.0.0
  +-- fs-extra@0.30.0
  | +-- graceful-fs@4.1.15 deduped
  | +-- jsonfile@2.4.0
  | | `-- graceful-fs@4.1.15 deduped
  | +-- klaw@1.3.1
  | | `-- graceful-fs@4.1.15 deduped
  | +-- path-is-absolute@1.0.1
  | `-- rimraf@2.4.5 deduped
  +-- globby@7.1.1
  | +-- array-union@1.0.2 deduped
  | +-- dir-glob@2.2.2
  | | `-- path-type@3.0.0
  | |   `-- pify@3.0.0
  | +-- glob@7.1.3 deduped
  | +-- ignore@3.3.10
  | +-- pify@3.0.0 deduped
  | `-- slash@1.0.0
  +-- p-map@1.2.0
  +-- p-try@1.0.0
  +-- pify@3.0.0
  +-- run-applescript@3.2.0
  | `-- execa@0.10.0
  |   +-- cross-spawn@6.0.5
  |   | +-- nice-try@1.0.5
  |   | +-- path-key@2.0.1 deduped
  |   | +-- semver@5.7.0
  |   | +-- shebang-command@1.2.0 deduped
  |   | `-- which@1.3.1 deduped
  |   +-- get-stream@3.0.0 deduped
  |   +-- is-stream@1.1.0 deduped
  |   +-- npm-run-path@2.0.2 deduped
  |   +-- p-finally@1.0.0 deduped
  |   +-- signal-exit@3.0.2 deduped
  |   `-- strip-eof@1.0.0 deduped
  +-- uuid@3.3.2
  `-- xdg-trashdir@2.1.1
    +-- @sindresorhus/df@2.1.0
    | `-- execa@0.2.2
    |   +-- cross-spawn-async@2.2.5
    |   | +-- lru-cache@4.1.5 deduped
    |   | `-- which@1.3.1 deduped
    |   +-- npm-run-path@1.0.0
    |   | `-- path-key@1.0.0 deduped
    |   +-- object-assign@4.1.1 deduped
    |   +-- path-key@1.0.0
    |   `-- strip-eof@1.0.0 deduped
    +-- mount-point@3.0.0
    | +-- @sindresorhus/df@1.0.1
    | +-- pify@2.3.0 deduped
    | `-- pinkie-promise@2.0.1 deduped
    +-- pify@2.3.0 deduped
    +-- user-home@2.0.0
    | `-- os-homedir@1.0.2
    `-- xdg-basedir@2.0.0
      `-- os-homedir@1.0.2 deduped


```
What's more, from the error stack, the error line related to `util.js` is just an simple import of another file. No more information can be found.
So maybe this is related to atom or electron. Please try to update the atom to latest. If error still happen, maybe i should build a same environment of yours :P .

**Comment by waipeinan** [comment]
bump

**Comment by mohvahedi20** [comment]
Oh my god, why is this for ?

**Comment by mslipets** [comment]
em.. bump?!
